# Generated by Django 5.2.13 on 2026-05-04 20:26

import core.storages
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='Auto-generated from the title on save. Supports Unicode (e.g. Bengali). Leave blank unless you need a custom URL.', max_length=220, unique=True)),
                ('issue_number', models.PositiveIntegerField()),
                ('cover_image', models.ImageField(help_text='Cover photo. Stored in the public bucket; URL is public + cacheable.', storage=core.storages.public_media_storage, upload_to='covers/')),
                ('pdf_file', models.FileField(help_text='PDF of the issue. Stored in the private bucket; .url generates a short-lived signed URL. Never expose the raw key to anonymous users.', storage=core.storages.private_media_storage, upload_to='pdfs/')),
                ('published_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_free', models.BooleanField(default=True, help_text='If True, the issue is readable without a Purchase record.')),
                ('price', models.PositiveIntegerField(default=20, help_text='Price in BDT. Ignored when is_free=True.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='magazines.category')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ['-published_date', '-issue_number'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.PositiveIntegerField(help_text='BDT amount actually paid, snapshotted at purchase time. Independent of future Issue.price changes — preserves audit trail.')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', help_text='Lifecycle of this purchase. Flipped by the gateway IPN.', max_length=10)),
                ('transaction_id', models.CharField(blank=True, help_text='Gateway-side transaction reference (SSLCommerz tran_id, bKash trxId, etc.). Nullable while a payment is still being initiated.', max_length=100, null=True, unique=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='magazines.issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-purchased_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'issue'), name='unique_user_issue_purchase')],
            },
        ),
    ]
