# Generated by Django 5.2.13 on 2026-04-29 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='price',
            field=models.PositiveIntegerField(default=20, help_text='Price in BDT. Ignored when is_free=True.'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='is_free',
            field=models.BooleanField(default=True, help_text='If True, the issue is readable without a Purchase record.'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='magazines.issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-purchase_date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'issue'), name='unique_user_issue_purchase')],
            },
        ),
    ]
