# Generated by Django 5.2.13 on 2026-04-29 20:24

import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0003_purchase_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='cover_image',
            field=models.ImageField(help_text='Cover photo. Stored in the public bucket; URL is public + cacheable.', storage=core.storages.public_media_storage, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='pdf_file',
            field=models.FileField(help_text='PDF of the issue. Stored in the private bucket; .url generates a short-lived signed URL. Never expose the raw key to anonymous users.', storage=core.storages.private_media_storage, upload_to='pdfs/'),
        ),
    ]
