# Generated by Django 5.2.13 on 2026-05-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0005_issue_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchased_at'], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase_date',
            new_name='purchased_at',
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', help_text='Lifecycle of this purchase. Flipped by the gateway IPN.', max_length=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Gateway-side transaction reference (SSLCommerz tran_id, bKash trxId, etc.). Nullable while a payment is still being initiated.', max_length=100, null=True, unique=True),
        ),
    ]
